media: images

components:
  text_editor:
    label: Text Editor
    fields:
      - name: content
        label: Content
        type: rich-text
  
  hero_block:
    label: Hero Section
    fields:
      - name: heading
        label: Heading
        type: text
      - name: image
        label: Image
        type: image

content:
  - name: pages
    label: Pages
    type: collection
    path: src
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: blocks
        label: Page Blocks
        type: blocks
        options:
          components:
            - text_editor
            - hero_block