media: images

components:
  text_editor:
    label: Text Editor
    fields:
      - name: content
        label: Content
        type: rich-text
  
  hero_block:
    label: Hero Section
    fields:
      - name: heading
        label: Heading
        type: text
      - name: image
        label: Image
        type: image

content:
  - name: pages
    label: Pages
    type: collection
    path: src
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: blocks
        label: Page Blocks
        type: block
        list: true
        blocks:
          - name: text_editor
            label: Text Editor
            component: text_editor
          - name: hero
            label: Hero
            component: hero_block
      - name: contact
        label: Contact information
        type: object
        fields:
          - name: first_name
            label: First name
            type: string
          - name: last_name
            label: Last name
            type: string
          - name: email
            label: Email address
            type: string
          - name: phone
            label: Phone number
            type: string