media: images

components:
  text-editor:
    label: Text Editor
    fields:
      - name: content
        label: Content
        type: rich-text
  
  hero-block:
    label: Hero Section
    fields:
      - name: heading
        label: Heading
        type: text
      - name: image
        label: Image
        type: image

content:
  - name: pages
    label: Pages
    type: collection
    path: src
    filename: "{primary}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: seo-description
        label: SEO Description
        type: text
        required: true
        description: Add a description of the page describing its content, that is 145 characters or less. This description can be displayed in search results on Google and other search engines.
        options:
          maxlength: 145
      - name: blocks
        label: Page Blocks
        type: block
        list: true
        blocks:
          - name: text-editor
            label: Text Editor
            component: text-editor
          - name: hero
            label: Hero
            component: hero-block