media: images

components:
  text-editor:
    label: Text Editor
    fields:
      - name: content
        label: Content
        type: rich-text
  
  hero-simple:
    label: Simple Hero
    fields:
      - name: heading
        label: Heading (H1)
        type: text
        required: true
      - name: subheading
        label: Subheading
        type: rich-text

  hero-with-image:
    label: Hero with Image
    fields:
      - name: heading
        label: Heading (H1)
        type: text
        required: true
      - name: subheading
        label: Subheading
        type: rich-text
      - name: bg_image
        label: Background Image
        type: image
        required: true

content:
  - name: pages
    label: Pages
    type: collection
    path: src
    filename: "{primary}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: seo_description
        label: SEO Description
        type: text
        required: true
        description: Add a description of the page's content that is 145 characters or less. This description can be displayed in search results on Google and other search engines. If you don't want Google to index this page, enter "no-index".
        options:
          maxlength: 145
      # HERO SECTION - Required, choose one type
      - name: hero
        label: Hero Section
        type: block
        list: 
          min: 1
          max: 1
        blocks:
          - name: hero-simple
            label: Simple Hero
            component: hero-simple
          - name: hero-with-image
            label: Hero with Image
            component: hero-with-image
      # CONTENT - Optional flexible blocks
      - name: blocks
        label: Blocks
        type: block
        list: true
        blocks:
          - name: text-editor
            label: Text Editor
            component: text-editor